


ALTER TABLE claims_form4
ADD COLUMN unique_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;


ALTER TABLE claims_form3
ADD COLUMN unique_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE `esoa` ADD `ref_id` VARCHAR(50) NOT NULL AFTER `id`;

ALTER TABLE `claims_form4` CHANGE `id` `ref_id` VARCHAR(50) NOT NULL;

ALTER TABLE `claims_form5` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT, add PRIMARY KEY (`id`);

ALTER TABLE `claims_form5` ADD `ref_id` VARCHAR(50) NOT NULL AFTER `id`;